version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  edge:
    build:
      context: .
      dockerfile: Dockerfile-edge
    container_name: edge-container
    restart: always
    depends_on:
      - mosquitto

  centralized:
    build:
      context: .
      dockerfile: Dockerfile-central
    container_name: central-container
    restart: always
    depends_on:
      - mosquitto
